COMMON: &common
  DEBUG: False
  SQLALCHEMY_TRACK_MODIFICATIONS: False

development:
  <<: *common
  DEBUG: True
#  SQLALCHEMY_DATABASE_URI: 'sqlite://'
#  SQLALCHEMY_DATABASE_URI: 'sqlite:///device_db.sqlite'
  SQLALCHEMY_DATABASE_URI: 'mysql://{0}:{1}@localhost/bdlab4'

production:
  <<: *common
  SQLALCHEMY_DATABASE_URI: 'mysql://{0}:{1}@localhost/bdlab4'

ADDITIONAL_CONFIG:
  MYSQL_ROOT_USER: root
  MYSQL_ROOT_PASSWORD: 12QWErty21
